apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-norb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-norb@sha256:b7c694ac4f2d0d30b5351738dadd8b7ebe8345e3dbd805e52a22b9e0d8c52277
        name: my-nodejs
        resources: {}
status: {}
